config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bus_stops, except: [:update, :edit, :destroy]
  root 'bus_stops#index'
  get '/search' => 'bus_stops#search', :as => 'search_page'

  resources :reports, except: [:update, :edit, :destroy]
  root 'reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_stop.rb
class BusStop < ApplicationRecord
    
end

app/models/bus_stop_location.rb
class BusStopLocation < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bus_stops_controller.rb
class BusStopsController < ApplicationController
  def index
    @busStops = BusStop.order('created_at DESC')
  end

  def new
    @busStop = BusStop.new
  end

  def create
    @busStop = BusStop.new(bus_stop_params)
    if @busStop.save
      flash[:success] = "Bus Stop added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
      @busStop = BusStop.find(params[:id])
      #@busStop = BusStop.find_by(:name => params[:name])
  end

  
  def search
      if params[:search].blank?
          redirect_to(root_path, alert: "Empty field!") and return
          else
          @parameter = params[:search].downcase
          @results = BusStop.where("lower(name) LIKE :search", search: "%#{@parameter}%")
          
      end
  end
  
  private

  def bus_stop_params
    params.require(:bus_stop).permit(:title, :address, :visited_by)
  end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.order('created_at DESC')
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      flash[:success] = "Report added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def report_params
    params.require(:report).permit(:complaint, :visited_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bus_stops/_bus_stop.html.erb
<li>
  <%= link_to bus_stop.name, bus_stop_path(bus_stop) %>
  serving <strong><%= bus_stop.routes_served %></strong>
  in the direction of <strong><%= bus_stop.direction %></strong>
</li>

app/views/bus_stops/_form.html.erb
<%= form_for @report do |f| %>
  <fieldset class="form-group">
    <%= f.label :stop_name, 'Bus Stop' %>
    <%= f.text_field :stop_name, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :visited_by, 'Scout ID' %>
    <%= f.text_field :visited_by, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :complaint, 'Complaint' %>
    <%= f.text_field :complaint, class: "form-control" %>
  </fieldset>

  <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

app/views/bus_stops/_header.html.erb
<%= form_tag(search_page_path, :method => "get",
    class: 'navbar-form navbar-left') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>

app/views/bus_stops/_report.html.erb
<li>
  <%= link_to report.stop_name, report_path(report) %>
  visited by <strong><%= report.visited_by %></strong>
</li>

app/views/bus_stops/index.html.erb
<html>
    <head>
        <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
    </head>

<%= render '/layouts/header' %>


    <div class="container">
        <header><h1 class="display-4">Search for your stop using a street name:</h1></header>
            <%= form_tag(search_page_path, :method => "get",
                class: 'navbar-form navbar-left') do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], placeholder: "e.g. 'Halsted'", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
                </div>
              </div>
            <% end %>

    </div>

<br>
<br>


<div class="container">
        <br>
        <h3>Here's all of the bus stops:</h3>
        <ul>
        <%= render @busStops %>
        </ul>
</div>

</html>

app/views/bus_stops/new.html.erb
<header><h1 class="display-4">Notify others about what's happening at your bus stop</h1></header>

<%= render 'form' %>

app/views/bus_stops/search.html.erb
<%= render '/layouts/header' %>
<div class="container">
<h1>Search Result</h1>

    <%= render @results  %>
        <br>
</div>

app/views/bus_stops/show.html.erb
<%= render '/layouts/header' %>
<div class="container">
    <header><h1 class="display-4"><%= @busStop.name %> </h1></header>

    <p>Coordinates: <%= @busStop.latitude %> <%= @busStop.longitude %></p>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&zoom=17&markers=#{@busStop.latitude}%2C#{@busStop.longitude}&key=AIzaSyCjSZ6Xz70elyGUyWVH4mV7OyXWshRYhXY" %>


    <%# citation:  https://medium.com/@pai.sarah89/displaying-google-static-map-with-geocoder-gem-8b128ec9c8ba %>
</div>

<br>
<br>

<div class="container">
<header><h1 class="display-4">Reports</h1></header>

  <p>Dear BusScout,<br>Your community is counting on you!

  </p>
  <br>
  <%= link_to '<DEPRECATED> Add your report here.', new_bus_stop_path, class: 'btn btn-primary btn-lg' %>






</div>
</div>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">BusScout Beta</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", root_path %></li>

            </ul>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>